# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'pokemon-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pokemon-app
  pod 'Alamofire'

  target 'pokemon-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pokemon-appUITests' do
    # Pods for testing
  end

end
